[options] 
; addons模块的查找路径（可以配多个，多个之间以逗号分隔）
addons_path = E:/code/2024/o_doo/addons
; 数据库管理密码(用于创建、还原和备份数据库等操作)
admin_passwd = 123123
; data目录, 用于存放session数据、附件、缓存文件等
;data_dir = /home/odoo/.local/share/Odoo
;csv读取格式
;csv_internal_sep = ,

;##################### 数据库相关配置 ####################
; 数据库主机名
db_host = localhost
; 数据库端口号，False为默认
db_port = 5432
; 数据库用户名
db_user = odoo
; 数据库用户密码
db_password = 123123
